# Copyright (c) 2018 Trough Creek Holdings, LLC.  All Rights Reserved

USER_VARIABLES:=$(foreach V, $(filter-out .% MAKE% %_template, $(sort ${.VARIABLES})), $(if $(filter-out environment% default automatic, $(origin $V)), $V))
export $(filter CURDIR REVISION DOCKER% BUILD%, ${USER_VARIABLES})
