#! /bin/bash
# Copyright (c) 2017, 2018 Trough Creek Holdings, LLC.  All Rights Reserved

set -e

for v in BUILD_DATE BUILD_ROOT CURDIR DOCKER_NS REVISION
do
	if test -z "${!v}"
	then
		echo "Missing variable: $v"
		exit 1
	fi
done

force=""
build_args=""

while [[ $# -gt 1 ]]
do
	case "$1" in
        -a|--build-arg) build_args="$build_args --build-arg $2"; shift ;;
	-f|--force) force="true"; ;;
	*) echo "Unknown option \"$1\"" 1>&2 ; exit 1 ;;
	esac

	shift
done


docker_name="$1"

docker_time_stamp="${CURDIR}/build/.stamp.time.${docker_name}"
docker_rev_stamp="${CURDIR}/build/.stamp.revision.${docker_name}"
docker_image="${DOCKER_NS}:${docker_name}-${REVISION}"

current_commit_id=`git rev-parse HEAD`

build_time=`docker inspect --format '{{index .Config.Labels "build_time"}}' ${docker_image} 2> /dev/null || echo ''`

if test -z "${force}" && test -f "${docker_rev_stamp}" && test -s "${docker_rev_stamp}" && cmp -s "${BUILD_ROOT}/REVISION" "${docker_rev_stamp}" && test -f "${docker_time_stamp}" && test -s "${docker_time_stamp}" && test -n "${build_time}" && (echo "${build_time}" | cmp -s "${docker_time_stamp}")
then
	echo "Nothing to do for ${docker_image}"
else
	echo "Building ${docker_image}"
	cd ${BUILD_ROOT}
	echo docker build ${DOCKER_SQUASH} -f "${CURDIR}/build/Dockerfile.${docker_name}" --label "revision=${REVISION}" --label "build_time=${BUILD_DATE}" --label "commit_id=${current_commit_id}" -t "${docker_image}" .
	docker build ${DOCKER_SQUASH} -f "${CURDIR}/build/Dockerfile.${docker_name}" --label "revision=${REVISION}" --label "build_time=${BUILD_DATE}" --label "commit_id=${current_commit_id}" --label "docker_ns=${DOCKER_NS}" -t "${docker_image}" .

	echo "${REVISION}" > "${docker_rev_stamp}"
	echo "${BUILD_DATE}" > "${docker_time_stamp}"
fi
